// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbXPbuBH+Kxj2Zu5uKurNiuLoSydn+RKlseM6zt1cY9cHkUsJCQggAGhZ59F/7yxA",
	"UqRIOc61cfOh30QS2Dc8++wudBdEMlVSgLAmmNwFimqaggXtns7ByExHMIvPqF3imxhMpJmyTIpgErwT",
	"7FMGhMUgLEsYaCITYpdAdL4x6ARwS1PFIZgEg+EBjJ6Mn4Zw+GweDobxQUhHT8bhaDgeD0aDp6N+vx90",
	"AoaSFerrBIKmuFOXdgSdQMOnjGmIg4nVGXQCEy0hpd54a0Hj9n+9p+Ef/fDZ1Q/5j/Dqrt8ZDzbF+x//",
	"9l3QCexaoXhjNROLYLPZFNKc98daS910+vznI/L0sP+UYOQ4o8ISwJXotJLCoNNKSwXaMjB+v6WMNyW9",
	"zFIqQg00pnMOBG4Vp4LiR2IURCxhEbGS2CUzREZRpjWInZheLIF8j1H6niQMeEyYIUWAyDyzZEUNEdIS",
	"peUNiyFueo0RN5ai5OYBn8+IhgScYpJI7Y0prfOO77Gt576a3gPPPZE6pTaYBJlmYam0zV5jqc1MSzwv",
	"Ls6I/0giGdesGfX7pSQmLCxAoyjLLG/x++1SakuW9fMxWZpSvS4wrrScc0hrLs/EDeUsJjOhMttmun9x",
	"f5jzdFozsXCKfJDdzqqupbXKTHq9OEq7+dtuJNMi6sybErLclIeGd1PNsPdBrtbH6apcLecfILLo0Uug",
	"vI0b/PviOAwTCw5Wiio11LNEtVLMERVSsIhygt/v5ZeltwTtp/EbwdcFQzwcQFWbW2SvPxuucqvzphGv",
	"TnAbUlBhaf+WtQxuz1246gSKZ5ryUjOKLGNYMh8Ti4xTXfU916c4jSAFYbsIDyZ7+QK097yivO7/zxnn",
	"ZWyJBqXBgLCOkhrnRRVyCuXX+6KJ3FQsKnBAEwvaHSFyCLKVQym1SFdrciY5i9bkWCyYgO5DjjKilnK5",
	"uGYW0uuCyK5Z3G5Otq9g5WIIiiElH1YRMH42fjIYxEk4SKJ5OErG4/CQxk9CCvPD4WFycHhAkcVSJl6D",
	"WCCUB23maqAWri1LW8J/wVIwlqaKrJYgakB3PJ4wbSzxIuJqSmP8QifzARFri02zkHuuB3L+H1TylN4W",
	"sRgf7Ibmi4v1Zx1rJ5DCAc8fWw9rDhVhfnCx+rwxvt7qa9/C7Fp1SlMosPcW9A2LgJzlW2qWfczmcMO0",
	"DQfDgwdRm4LIZWccM9RF+Vkla/2mnVqXqy+Kum9AEsm5XGEJkqK01GRKSY25avJNqP9S5E0T+eGXk7cK",
	"og45ksJSJkD7xym1dE4N+CepyRHPjPVff+xeCp83VUMHLZUmU/Gfzx1OjSVewp9PHcdV10WIv7kwXmBv",
	"hg9kSQ2ZA4gKu1IREyWNYXO+JmlmC8qdHp3s0O6leOn7EOvYOQOS0jWJWZIgL2iZbvnb95w/SM0WTFBO",
	"sLMSzvHc1cyAzk94T3SL890ppHt5PYf4F5fWbYrfFT+vWbyp1dpyTVArrpVuY195LZdUC+xrZmwTKGcU",
	"Y4XR58xYDFRVbb3GCri114ou4NrKjyBaYI+vHVlrsJrBTdE04k6CO3MFGbf1jgbWr9Q/j2bj2Yfj9cnw",
	"Xf/04reD17++G735dWZPLl59PFkPlqfTd8PXF/9Yn3747fZ0enxwOn2+Ojl69ayts906MbkL8NTcj+80",
	"JMEk+EtvO2b2cpj3ytJS9sUB1ZquG1jYim42oBs3vyQSlUWYLhGGfLNLcg7lxaGR52czEpIjLKSIVUyN",
	"lAq68F9lUlY9U2QV7mAYOVxhXIS34hIuV4QaEkPCBMSEOf65FKgUxBKR69bh2UpDuc8HziLAaRGP2Y+5",
	"zxWNlkCGXawwmeaVJn+1WnWp+9yVetHL95re69nR8enb43DY7XeXNuWVmSbYGniyde752SzoBDegjQ/M",
	"zYBytaQD3CgVCKpYMAkOuv3uKO9i3TkW/ePkLliA3ds5R0uIPjo41gPeMABB7oI/i4NJ8ALsy23z7qdo",
	"p3bY7xcHC8LmXSfPybX3wUiXEtsbgPvg9rLogBvgePN3B7l8vtvxBrFOF7XuHBf3anhvjck52EwLQ2gz",
	"0cmK4TCjfIUmCeMWXCLtRgYp5LxKD5X7mfeN9t2JKUZ9TRys8guVTxno9fZGRW17jW30GqPNroITesvS",
	"LCUiS+e+d86ZhSjUSxf71KX01tOYYX9ATWcMCc24DSYDHNBTr6B4YiJ/ao7uTeO2VKg8w/qhpdX7LaPe",
	"5//VV0RjrUa0YPJtFkVgTJJxUiICc3R0rw35ncRfv8wWf9HVYsRPNHa3SWBcA1ae1WPpfyfgVkGEtRLy",
	"NdU0xdgRWhlZTSVZy4p8hd24bKvErgAAoUTAqpTRvRRv8rzk67ybWxNKIs5A2JAawxZI8rMpuRQ3jLpa",
	"8DuLfycOZKTM0C6ZJbWrt46vCtjzgSYrxjlZgMCzBUIFmU19XagTgLexMoXdywCF5WhdMcFVupe2XPAt",
	"1b471C+8QL3yhRuM/UnG6/96sniM1C+AN40kHXwlvXvmynwed10Ew7YbWzB35lhiIX70rC0uIf3Nn9P+",
	"7PG0H0mRcBZZEpbIm00J5dj+r7E1yozr+EbD4eMZ9Ysfg7DZg9sIVMGm3xqjlYxUHTmahFbrP7bzzCze",
	"eJLjYKGtH0nlTVU4jn845M2mDdqZOhn7aafN+e2S3s4fRy2VdHTPTY13ICamrIF8/T/LotnUzeucFZk8",
	"ejwbyohgGUlkJuJvEbQeK4Tml/yfwW6nvVl+ARaL4C408wvbFoS+APsV4dl/lBryTTR5/wf6Q4HuMPow",
	"lLuNrtHzgPTTfI8q1ttO3Ffl1sYdUdvkXELENP8ZD5rzUG0kb9tb/CV0tfl3AAAA//9MY1jKBiAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
