// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW3PbuBX+Kxh0Z3Z3KupmRXH00slK2USp7bi+7M42dr0QeSghAQEEAHVZj/57BwBJ",
	"kSLtKNvGzUPfRBI4N3znO+dA9zgUiRQcuNF4dI8lUSQBA8o9XYAWqQphGp0Ts7BvItChotJQwfEIX3P6",
	"KQVEI+CGxhQUEjEyC0Aq24hbGNYkkQzwCPf6RzB4NnwewPGLWdDrR0cBGTwbBoP+cNgb9J4Put0ubmFq",
	"JUurr4U5SexOVdiBW1jBp5QqiPDIqBRaWIcLSIg33hhQdvu/3pPgj27w4vaH7Edwe99tDXvb/P2Pf/sO",
	"t7DZSCteG0X5HG+321ya8/6VUkLVnb74eYyeH3efIxs5Rgk3COxK67QUXFunpRISlKGg/X5DKKtLepMm",
	"hAcKSERmDBCsJSOc2I9ISwhpTENkBDILqpEIw1Qp4HsxvVoA+t5G6XsUU2ARohrlAUKz1KAV0YgLg6QS",
	"SxpBVPfaRlwbYiXXD/hiihTE4BSjWChvTGGdd/wB2zruq+4ceO6xUAkxeIRTRYNCaZO92hCT6oZ4Xl2d",
	"I/8RhSKqWDPodgtJlBuYg7KiDDWswe/LhVAGLarno9MkIWqTY1wqMWOQVFye8iVhNEJTLlPTZLp/8XiY",
	"s3TaUD53inyQ3c6yroUxUo86nShM2tnbdiiSPOrUmxLQzJRDw7stZ9h7nKn1cbotVovZBwiN9egNENbE",
	"Df59fhya8jkDI3iZGqpZIhspZky44DQkDNnvj/LLwlti7SfRO842OUMcDqCyzQ2yN58NV7HVeVOLVwuv",
	"AwIyKOzfsZa22zMXbltYslQRVmi2IosYFsxH+TxlRJV9z/RJRkJIgJu2hQcVnWyBtfeipLzq/88pY0Vs",
	"kQKpQAM3jpJq5xUSQ5iY31EDyV1OIXc0qou1JJU+VCoyMciKQQUTlWM/fDF81utFcdCLw1kwiIfD4JhE",
	"zwICs+P+cXx0fES6TbkWKiAG7gxNGly9ogloQxKJVgvgFVA5zoyp0gZ5EVE5fSJiIHAyDwBaUzTqRdPz",
	"KqCL/6BqJmR9AnxuU2h41MIJ5fljr/XlhfGzjjUna+6Az9WdhxWH8jAfXBg+b4yvberOtwv7Vp2RBHK0",
	"XYJa0hDQebalYtnHdAZLqkzQ6x8dojf35AC9jYQVQyQUCZbJQZwlIbQ6SBRRq4Cw81I6+k17RSzzNa/W",
	"vrOIBWNiZWuL4IV5OpVSKAMR0tkmq/+GZ90Q+uGX00sJYQuNBTeEclD+cUIMmREN/kkoNGapNv7rj+0b",
	"jhsKRiqjP5+WjGiDvIQ/m5V7jP0gjWUh/2IO3+H7vgAIjbYVUi/W4AqLl1DyEI8XS8pMfkK1qcfynMwp",
	"t4FCjGpjj7qstkrmHNbmTpI53BnxEXjDwdjXjqkUGEVhmXcndieyOzMFKTPV0gmbt/Kf4+lw+uHV5rR/",
	"3T27+u3o5Nfrwbtfp+b06u3H001vcTa57p9c/WNz9uG39dnk1dHZ5OXqdPz2BX4k65zd9tTcj+8UxHiE",
	"/9LZzTOdDL2dgleLBgwTpcimhoWd6Hqns3WNcixc6bNZENqQb/eTbjI+Ref5oaGX51MUoLGtIjb3CI9Q",
	"QjiZ+68iLihft2/4lW2t7Q5qI2dXaBfhnbiYiRUiGkUQUw4Roi5DbrhVCnxhkevW2bMVmjCfgYyGYMcS",
	"e8x+nnopSbgA1G9bek0VK3WTq9WqTdzntlDzTrZXd06m41dnl6+CfrvbXpiElZpnvDPwdOfcy/MpbuEl",
	"KO0Ds+wRJhekZzcKCZxIikf4qN1tD7J2yZ1j3qiM7vEczIMtWriA8KODYzXgNQMsyF3wpxEe4ddg3uy6",
	"RD+uObX9bjc/WOBOLZGSZZzZ+aCFS4ndqPkY3N7krVYNHO/+7iCXDRJ73lisk3mlDbSLOxW8N8bkAkyq",
	"uEaknuhoRW3XLH3FQDFlBlwi7UfGUshFmR5KFwHva32iE5PPlAo5WGWT+6cU1GY3ustdod1Fr8bI+wpO",
	"yZomaYJ4msx8q5gxC5JWL5k/pC4ha09jmv4BFZ0RxCRlBo96dhJMvIL8ifLsqT4j1o3bUaH0DOu740bv",
	"d4z6mP+3XxGNlRrRgMnLNAxB6zhlqECEzdHBozZkw+9fv8wWf6PSYMRPJHLXFqBdi1Cc1VPpv+awlhDa",
	"WgnZmnKa2tghUpqNdClZi4p8a1tR0VSJXQEARBCHVSGjfcPfZXnJNlmTtkEEhYwCNwHRms4tyU8n6IYv",
	"KXG14Hca/Y4cyFCRoW00jSt3PC1fFWwrBwqtKGNoDtyeLSDC0XTi60KVALyNpRHkUQbILbfW5eNLqXtp",
	"ygXfUj10WfeFN3W3vnCDNj+JaPNfTxaPkepN47aWpL2vpPeBoSobRl0XQTWagW3B3JnbEgvRk2dtftvl",
	"r5ic9hdPp30seMxoaFBQIG86QYTZ9n9jW6NUu45v0O8/nVG/2ID4Zg/WIcicTb81RisYqTxy1Amt0n/s",
	"5plptPUkx8BAUz+SiGVZOJptEDUaTSc12pk4GQ/TTpPzuyWdvX8oGirp4JFrCu9AhHRRA9nmf5ZF04kb",
	"wxnNM3nwdDYUEbFlJBYpj75F0HqsIJLdJn8Gu63mZvk1GFsE96GZ3U82IPQ1mK8Iz+6T1JBvosn7P9AP",
	"BbrD6GEodxtdo+cB6af5DpG0s5u4b4uttTuipsm5gIiu/wWL6/NQZSRv2pv/93C7/XcAAAD//0v4rYBv",
	"HgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
