// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbXPbNhL+KxheZ9rOiXqzojj6cpNabqNc7Ohs5zq92OdC5FJCAgIIAFpWPfrvNwuQ",
	"FCnSjttrfPlw30QS2Dfs8+wudBdEMlVSgLAmmNwFimqaggXtns7AyExHMIvn1K7wTQwm0kxZJkUwCd4J",
	"9ikDwmIQliUMNJEJsSsgOt8YdAK4paniEEyCwfAARs/Gz0M4fLEIB8P4IKSjZ+NwNByPB6PB81G/3w86",
	"AUPJCvV1AkFT3KlLO4JOoOFTxjTEwcTqDDqBiVaQUjQupbdvQCzR0vFBJ0iZKB4HHZRoQaPsf7+n4W/9",
	"8MXVd/mP8Oqu3xkPtsX77//2TdAJ7EahbmM1E8tgu90WqlxojrWWuhmRsx+PyPPD/nOCYeWMCksAV2JE",
	"lBQGI6K0VKAtA+P3W8p4U9KrLKUi1EBjuuBA4FZxKih+JEZBxBIWESuJXTFDZBRlWoPYC/jFCsi3GMJv",
	"ScKAx4QZUkSPLDJL1tQQIS1RWt6wGOKm13gcxlKU3Dz9sxnRkIBTTBKpvTGldd7xe2zrua+m98ikSKRO",
	"qQ0mQaZZWCpts9dYajPTEs+LiznxH0kk45o1o36/lMSEhSVoFGWZ5S1+n6+ktmRVPx+TpSnVmwIASssF",
	"h7Tm8kzcUM5iMhMqs22m+xcPhznH2oaJpVPkg+x2VnWtrFVm0uvFUdrN33YjmRZRZ96UkOWmPDa82yr8",
	"3ge5Wh+nq3K1XHyAyKJHr4DyNuLw74vjMEwsOVgpqrxRR4lq5Z8jKqRgEeUEvz9IPitvCdpP47eCbwr6",
	"eHwCVW1ukb35bLjKrc6bRrw6wW1IQYWl/d5vZC2D23MXrjqB4pmmvNSMIssYlrTIxDLjVFd9z/UpTiNI",
	"QdgupgeTvXwB2ntWUV73/8eM8zK2RIPSYEBYR0mN86IKOYXy6/uiidxULCrygCYWtDtC5BBkK5el1CJd",
	"bchcchZtyLFYMgHdxxxlRC3lcnnNLKTXBZFds7jdnOy+apaLISiGlHxYzYDxi/GzwSBOwkESLcJRMh6H",
	"hzR+FlJYHA4Pk4PDA4osVq9ITXM1UAvXlqUt4b9gKRhLU0XWKxC1RHc8njBtLPEi4iqkMX6hk/mIiLXF",
	"plnlPdcDOfsvyvyfW6w/61g7gRQOeP7YeVhzqAjzo4vV543x9VZf+/5m36pTmkKRe+egb1gEZJ5vqVn2",
	"MVvADdM2HAwPHkVtCiKHzjhmqIvyeQW1ftNercvVF0XdNyCJ5FyusQRJUVpqMqWkRqyafBPqvxR500S+",
	"++fJuYKoQ46ksJQJ0P5xSi1dUAP+SWpyxDNj/dfvu5fC46Zq6KCl0mQq/uPY4dRY4iX8UejsUf29zJMf",
	"wu8m/10S3hU/r1m8rVWDck1Qo/9KPbyvAJRLqiXgDTO2Gcs5XTLhKJkzY/Hwq2rrVUDArb1WdAnXVn4E",
	"0XIw+NrRiQarGdwUbQ3uJLgzV5BxW6+5sHmt/nU0G88+HG9Ohu/6pxe/HLz5+d3o7c8ze3Lx+uPJZrA6",
	"nb4bvrn4x+b0wy+3p9Pjg9Ppy/XJ0esXbb3XzonJXYCn5n58oyEJJsFferspqZfnc68kv7JzC6jWdNPI",
	"hZ3oZou0dR12IlFZhLiIMOTbfRhOj07IvDg08nI+IyE5QqpHNFIRk5QKuvRfZVLysuleigvsyXEHw8jh",
	"CuMivBOXcLkm1JAYEiYgJswh5FKgUhArzFy3Ds9WGso9JjmLAOcZPGY/pb1UNFoBGXaRAzPNK23oer3u",
	"Uve5K/Wyl+81vTezo+PT8+Nw2O13Vzblla472Bl4snPu5XwWdIIb0MYH5mZAuVrRAW6UCgRVLJgEB91+",
	"d5T3We4ciw5nchcswd7b20UriD66dKwHvGEAJrkL/iwOJsFPYF/t2ks/5zm1w36/OFgQNu+LeM6ivQ9G",
	"OkjsBtiH0u1V0aM1kuPt313K5RPInjeY63RZ6x9xca+W760xOQObaWEIbQKdrBm228rXEJIwbsEBaT8y",
	"SCFnVXqoXC+8bzSYTkwxjGri0iq/D/iUgd7sLgTUrhruotdg5H0FJ/SWpVlKRJYufHeXMwtRqJcu71OX",
	"0ltPY4b9BjWdMSQ04zaYDHCETL2C4omJ/Kk5XDaN21Gh8gzr2+pW73eM+pD/V18wG2s1oiUnz7MoAmOS",
	"jJMyIxCjowdtyKfmv/4+W/xVTIsRP9DY3XeAcS1CeVZPpf+dgFsFEdZKyNdUYYqxI7QyVJkKWMuKfIX9",
	"omyrxK4AAKFEwLqU0b0Ub3Nc8k3etm0IJRFnIGxIjWFLJPnZ9FLcMOpKwa8s/pW4HCMlQLtkltTuhjq+",
	"KGBvB5qsGedkCQKPFggVZDb1ZaGOf29iZUx4kAAKw8lsWo4YlealDQq+o3qiG8ArX9fB2B9kvPnTseRT",
	"qH69uW1gePCF9N4zGOUDpWsymCELwA7N5QRWYIifHNTFLVoF2KP++On0n3m9RMMHD+39mwlv0Yuns+hI",
	"ioSzyJKwRMtsSijHiWWD3VxmAOcq5a2M8uXOzuHw6ew8n5+d7Kp7zohfHy2XtFqdm5qsXGuidkPZLN56",
	"puZgoa2pSuVNVTimD7OGzKYN8pw6GfeTZ5vzuyW9vT9vWtqB0QMXIt6BmJiykPPN/wzrs6m7XeCs4JvR",
	"U+I9jwgWw0RmIv4/cNqB4/OV0Pw+/zP46bRPHT+BxXZiHx753WwLSn4C+wUh0n+SavtVdMtfL9i+tkR3",
	"Ofq4LHcbXcvsE9Jfi/SoYr3d1cVVubVx2dZ2BVGmiGn+Qx40B8va3Ubb3uLfn6vtfwIAAP//66XmxQ4g",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
