// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status string `json:"status"`
}

// Resource Full resource representation
type Resource struct {
	// ApprovalStatus The approval status after the spec is validated by Policy Engine.
	ApprovalStatus *string `json:"approval_status,omitempty"`

	// CatalogItemInstanceId The unique identifier of the catalog item instance
	CatalogItemInstanceId string `json:"catalog_item_instance_id"`

	// CreateTime Timestamp when the resource was first created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the Resource
	Id *string `json:"id,omitempty"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// ProviderName Name of the Service Provider
	ProviderName *string `json:"provider_name,omitempty"`

	// Spec Service specification following one of the supported service type
	// schemas (VMSpec, ContainerSpec, DatabaseSpec, or ClusterSpec).
	Spec map[string]interface{} `json:"spec"`

	// UpdateTime Timestamp when the resource was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// ValidSpec Service specification following one of the supported service type
	// schemas (VMSpec, ContainerSpec, DatabaseSpec, or ClusterSpec).
	// This Spec has been validated and possibly mutated by DCM Policy Engine.
	// Hence its value may differ from the spec field (original intention of the user).
	ValidSpec *map[string]interface{} `json:"valid_spec,omitempty"`
}

// ResourceList Paginated list of resources
type ResourceList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string    `json:"next_page_token,omitempty"`
	Resources     []Resource `json:"resources"`
}

// ResourceIdPath defines model for ResourceIdPath.
type ResourceIdPath = string

// ListResourcesParams defines parameters for ListResources.
type ListResourcesParams struct {
	// Provider Filter provider name
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`

	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateResourceParams defines parameters for CreateResource.
type CreateResourceParams struct {
	// Id Optional ID for the resource
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateResourceJSONRequestBody defines body for CreateResource for application/json ContentType.
type CreateResourceJSONRequestBody = Resource
