name: Subsystem Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  subsystem:
    uses: dcm-project/shared-workflows/.github/workflows/black-box.yaml@main
    with:
      up-target: subsystem-test-up
      test-target: subsystem-test
      down-target: subsystem-test-down
      images: "quay.io/sclorg/postgresql-16-c9s:latest wiremock/wiremock:3.13.2"